name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: { bun-version: 'latest' }
      - run: bun install
      - run: bunx ng build --configuration production
      - run: cp dist/familia-quiz/browser/index.html dist/familia-quiz/browser/404.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/familia-quiz/browser
          force_orphan: true

